import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { gsap } from "gsap"



import { library } from '@fortawesome/fontawesome-svg-core'

/* import all the icons in Free Solid, Free Regular, and Brands styles */
import { fas } from '@fortawesome/free-solid-svg-icons'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SideBar from "./components/SideMenu";
import SideMenuContextProvider from "@/context/SideMenuContext";

library.add(fas, far, fab)


const geistSans = Geist({variable: "--font-geist-sans", subsets: ["latin"],});

const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"],});

export const metadata = { title: "Create Next App", description: "Generated by create next app",};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased text-[14px]`}
    >
      
      <body className="min-h-full overflow-x-hidden">
        <SideMenuContextProvider>
          <SideBar />
          <Navbar />
          {children}
          <Footer />
        </SideMenuContextProvider>
      </body>
    </html>
  );
}
